/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cliente.vistas;

import com.cliente.controlador.ClienteSocket;
import com.server.modelo.Catalogo;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mariana
 */
public class VerCarrito extends javax.swing.JFrame {

    /**
     * Creates new form VerCarrito
     */
    private List carrito;
    private List list;
    private ClienteSocket service;
    
    public VerCarrito( List carrito,List list , ClienteSocket service) {
        initComponents();
        this.carrito = carrito;
        this.list = list;
        this.service = service;
           DefaultTableModel modelo = new DefaultTableModel();
           jtDatos.setModel(modelo);
            
            modelo.addColumn("Identificador");
            modelo.addColumn("Nombre");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Cantidad");
            modelo.addColumn("imagen");
            
            for (Object obj : carrito)
            {
                Catalogo cc = (Catalogo)obj;
                Object o[] = new Object[5];
                
                o[0] = cc.getId();
                o[1] = cc.getNombre();
                o[2] = cc.getDescripcion();
                o[3] = cc.getExitencias();
                o[4] = cc.getImg();
                
                modelo.addRow(o);
                
            }
            
//        Vamos a ocultar los campos de id y de la imagen para que no los vea el usuario pero nosotros los vamos a usar 
        jtDatos.getColumnModel().getColumn(0).setMaxWidth(0);
        jtDatos.getColumnModel().getColumn(0).setMinWidth(0);
        jtDatos.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        jtDatos.getColumnModel().getColumn(4).setMaxWidth(0);
        jtDatos.getColumnModel().getColumn(4).setMinWidth(0);
        jtDatos.getColumnModel().getColumn(4).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlIcon = new javax.swing.JLabel();
        jbExit = new javax.swing.JButton();
        jbQuitar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 560, 120));

        jButton1.setText("Finalizar la Compra ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 190, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Imagen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jlIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jlIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 220, 170));

        jbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        jbQuitar.setText("Quitar");
        jbQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitarActionPerformed(evt);
            }
        });
        getContentPane().add(jbQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/F0B.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 420));

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDatosMouseClicked

        //        Obtenemos el nomero de la columna seleccionada y sus valores respectivos
        int num = jtDatos.getSelectedRow();

        int id = (int)jtDatos.getValueAt(num, 0);
        String nombre = (String) jtDatos.getValueAt(num, 1);
        String descripcion = (String)jtDatos.getValueAt(num, 2);
        long existencias = (long)jtDatos.getValueAt(num, 3);

        
    }//GEN-LAST:event_jtDatosMouseClicked

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        
        try {
            new Compracliente(list , service,carrito).setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(VerCarrito.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitarActionPerformed
        
        
        int num = jtDatos.getSelectedRow();

        int id = (int)jtDatos.getValueAt(num, 0);
        String nombre = (String) jtDatos.getValueAt(num, 1);
        String descripcion = (String)jtDatos.getValueAt(num, 2);
//        long existencias = 1;
        byte[] img = (byte[]) jtDatos.getValueAt(num, 4);
        
        
        //Validacion de existencias
        
        for (Object obj : carrito)
        {
            
            Catalogo cc = (Catalogo)obj;
            
            if (cc.getId() == id)
            {
                if(cc.getExitencias() != 0)
                {
                    if (carrito != null)
                    {
                        for (Object o : list)
                         {
                             Catalogo cs = (Catalogo)o;
                             if(cs.getId() == id )
                             {
                                 cs.setExitencias(cs.getExitencias() + 1);
                                 list.remove(cs);
                                 list.add(cs);

                             }
                         }
                    }
                    else{
                        
                        JOptionPane.showMessageDialog(this, "No se ha comprado nada :/  ", "Error ", JOptionPane.ERROR_MESSAGE);
                        
                    }
                    
//                    ACtualiza la lita
                    cc.setExitencias(cc.getExitencias() - 1);
                    carrito.remove(cc);
                    carrito.add(cc);
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No hay mas articulos disponibles  ", "Error ", JOptionPane.ERROR_MESSAGE);
                    break;
                }
            }

        }
        
        DefaultTableModel modelo = new DefaultTableModel();
        jtDatos.setModel(modelo);
        modelo.addColumn("Identificador");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Existencias");
        modelo.addColumn("imagen");

        for (Object obj : list)
        {
            Catalogo cc = (Catalogo)obj;
            Object o[] = new Object[5];

            o[0] = cc.getId();
            o[1] = cc.getNombre();
            o[2] = cc.getDescripcion();
            o[3] = cc.getExitencias();
            o[4] = cc.getImg();

            modelo.addRow(o);

        }
    }//GEN-LAST:event_jbQuitarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VerCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VerCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VerCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VerCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VerCarrito().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbQuitar;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JTable jtDatos;
    // End of variables declaration//GEN-END:variables
}
